# modularbeit 1.0.0
#
# Runs Apache, PHP (+Redis) and phpMyAdmin
# SSL is preconfigured.
# Imagemagick and XDebug are activated.
#
# Run with 
# docker-compose up -d
#
# Basis von (c) 2020 Harald Schneider - Erweiterung und Anpassung (c)Bruno Thurnherr
#
version: '3'
services:

  # Lokale MySQL Datenbank
  mysql:
    container_name: modularbeit-mariadb
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: P99F-TBtgm2RgujbPVS!
      MYSQL_DATABASE: itwisse_lernplattform
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
      #MYSQL_USER: itwisse_lpf
      #MYSQL_PASSWORD: P99F-TBtgm2RgujbPVS!
    
    ports:
      - '3306:3306'
    volumes:
      - ./modularbeit/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql


  # PHP Erweiterung Apache Webserver
  php:
    container_name: modularbeit-php

    image: 'bitnami/php-fpm:7.4'
    depends_on:
      - redis
      - mysql
    volumes:
      - './modularbeit/www/:/app:delegated'
      - './modularbeit/php/php.ini:/opt/bitnami/php/etc/conf.d/php.ini:ro'
  
  # Apache Webserver
  apache:
    container_name: modularbeit-apache
    image: 'bitnami/apache:2.4'
    ports:
      - '8000:8080'
      - '443:8443'
    depends_on:
      - mysql
      - php
    volumes:
      - './modularbeit/www/:/app:delegated'
      - './modularbeit/apache/my_vhost.conf:/vhosts/myapp.conf:ro'
      - './modularbeit/apache/certs:/certs'
  redis:
    container_name: modularbeit-redis
    image: 'bitnami/redis:6.0'
    environment:
      - REDIS_PASSWORD=at15jx13
      
  # PHPmyAdmin Webanwendung zur Pflege der MySql Datenbank resp. Maria Datenbank
  phpmyadmin:
    container_name: modularbeit-phpmyadmin
    image: 'bitnami/phpmyadmin:latest'
    ports:
      - '8143:8443'
    environment:
      - DATABASE_HOST=itwisse.mysql.db.hostpoint.ch