name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
 
    env:
      PHP_EXTENSIONS: dom, json, libxml, mbstring, mysqli, soap, xml, xmlwriter, :apcu, :imagick
      PHP_INI_VALUES: memory_limit=-1, assert.exception=1, zend.assertions=1, error_reporting=-1, log_errors_max_len=0, display_errors=On

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6
        with:
          php_version: 7.4
          php_extensions: mysqli

      - name: composer install missing files
        run: composer install   

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          TEST_NAME: Unittests
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
