name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    sudo apt-get install php7.x-mysqli

    sudo service apache2 restart

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: Unittests
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text