name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6
        with:
          php_version: 7.4
          php_extensions: mysqli

      - name: Sleep for 120 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '120s'

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: Unittests
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: Unittests
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text