name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose up -d
        
      - name: Healthy Test
        run: docker run --network container:modularbeit-apache appropriate/curl -s --retry 10 --retry-connrefused https://localhost

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          TEST_NAME: Unittests
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
