

name: Check_Modularbeit
on: [push]
env:
  NODE_VERSION: 12.x

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check single, no redirect
      uses: ./
      with:
        url: https://www.modularbeit.ch
        max-attempts: 5
        retry-delay: 2s
